// Layer config sourced from brief §8–10.
// maxY: final upward translation in px at scroll progress = 1
// style: initial absolute position inside the sticky stage
// baseTransform: static rotation/scale applied on top of the scroll translate
// placeholderColor/Height: used until real WebP assets are placed

export const LAYERS = [
  {
    id: 'books',
    src: '/images/chemistry-hero/books-stack.webp',
    zIndex: 10,
    maxY: -180,
    width: '12vw',
    style: { top: '5vh', left: '-1vw' },
    label: 'Books',
  },
  {
    id: 'atom-model',
    src: '/images/chemistry-hero/atom-model.webp',
    zIndex: 12,
    maxY: -240,
    width: '9vw',
    style: { top: '5vh', left: '12vw' },
    label: 'Atom Model',
  },
  {
    id: 'chemistry-flask',
    src: '/images/chemistry-hero/chemistry-flask.webp',
    zIndex: 14,
    maxY: -280,
    width: '8vw',
    style: { top: '10vh', left: '23vw' },
    label: 'Flask',
  },
  {
    id: 'coffee-mug',
    src: '/images/chemistry-hero/mug.webp',
    zIndex: 20,
    maxY: -300,
    width: '11vw',
    style: { top: '3vh', right: '5vw' },
    label: 'Coffee Mug',
  },
  {
    id: 'grading-note',
    src: '/images/chemistry-hero/sticky-notes-2.webp',
    zIndex: 22,
    maxY: -560,
    width: '8vw',
    style: { top: '20vh', right: '7vw' },
    label: 'Grading Note',
  },
  {
    id: 'lesson-plan-notebook',
    src: '/images/chemistry-hero/lesson-plan.webp',
    zIndex: 30,
    maxY: -430,
    width: '27vw',
    style: { top: '6vh', right: '19vw' },
    label: 'Notebook',
  },
  {
    id: 'quiz-stack',
    src: '/images/chemistry-hero/quiz-stack.webp',
    zIndex: 35,
    maxY: -500,
    width: '25vw',
    style: { top: '8vh', left: '33vw' },
    label: 'Quiz Stack',
  },
  {
    id: 'safety-goggles',
    src: '/images/chemistry-hero/safety-goggles.webp',
    zIndex: 40,
    maxY: -560,
    width: '17vw',
    style: { top: '38vh', left: '4vw' },
    label: 'Safety Goggles',
  },
  {
    id: 'sticky-notes-curious',
    src: '/images/chemistry-hero/sticky-notes.webp',
    zIndex: 45,
    maxY: -620,
    width: '10vw',
    style: { top: '50vh', left: '14vw' },
    label: 'Be Curious',
  },
  {
    id: 'wooden-ruler',
    src: '/images/chemistry-hero/ruler.webp',
    zIndex: 50,
    maxY: -700,
    width: '22vw',
    style: { top: '62vh', right: '8vw' },
    baseTransform: 'rotate(-12deg)',
    label: 'Ruler',
  },
  {
    id: 'red-pen',
    src: '/images/chemistry-hero/red-pen.webp',
    zIndex: 55,
    maxY: -780,
    width: '15vw',
    style: { top: '68vh', right: '14vw' },
    baseTransform: 'rotate(-8deg)',
    label: 'Red Pen',
  },
]
