// Layer config sourced from brief §8–10.
// maxY: final upward translation in px at scroll progress = 1
// style: initial absolute position inside the sticky stage
// baseTransform: static rotation/scale applied on top of the scroll translate
// placeholderColor/Height: used until real WebP assets are placed

export const LAYERS = [
  {
    id: 'books',
    zIndex: 10,
    maxY: -180,
    width: '12vw',
    style: { top: '5vh', left: '-1vw' },
    placeholderColor: '#4a6741',
    placeholderHeight: '20vh',
    label: 'Books',
  },
  {
    id: 'atom-model',
    zIndex: 12,
    maxY: -240,
    width: '9vw',
    style: { top: '5vh', left: '12vw' },
    placeholderColor: '#7a7a8a',
    placeholderHeight: '13vh',
    label: 'Atom Model',
  },
  {
    id: 'chemistry-flask',
    zIndex: 14,
    maxY: -280,
    width: '8vw',
    style: { top: '10vh', left: '23vw' },
    placeholderColor: '#82b378',
    placeholderHeight: '15vh',
    label: 'Flask',
  },
  {
    id: 'coffee-mug',
    zIndex: 20,
    maxY: -300,
    width: '11vw',
    style: { top: '3vh', right: '5vw' },
    placeholderColor: '#a0784b',
    placeholderHeight: '13vh',
    label: 'Coffee Mug',
  },
  {
    id: 'grading-note',
    zIndex: 22,
    maxY: -560,
    width: '8vw',
    style: { top: '20vh', right: '7vw' },
    placeholderColor: '#f0d84a',
    placeholderHeight: '7vh',
    label: 'Grading Note',
  },
  {
    id: 'lesson-plan-notebook',
    zIndex: 30,
    maxY: -430,
    width: '27vw',
    style: { top: '6vh', right: '19vw' },
    placeholderColor: '#e8e0d0',
    placeholderHeight: '28vh',
    label: 'Notebook',
  },
  {
    id: 'quiz-stack',
    zIndex: 35,
    maxY: -500,
    width: '25vw',
    style: { top: '8vh', left: '33vw' },
    placeholderColor: '#f5f2ed',
    placeholderHeight: '25vh',
    label: 'Quiz Stack',
  },
  {
    id: 'safety-goggles',
    zIndex: 40,
    maxY: -560,
    width: '17vw',
    style: { top: '38vh', left: '4vw' },
    placeholderColor: '#c8d0d8',
    placeholderHeight: '9vh',
    label: 'Safety Goggles',
  },
  {
    id: 'sticky-notes-curious',
    zIndex: 45,
    maxY: -620,
    width: '10vw',
    style: { top: '50vh', left: '14vw' },
    placeholderColor: '#f5b8c4',
    placeholderHeight: '11vh',
    label: 'Be Curious',
  },
  {
    id: 'wooden-ruler',
    zIndex: 50,
    maxY: -700,
    width: '22vw',
    style: { top: '62vh', right: '8vw' },
    placeholderColor: '#c8a96e',
    placeholderHeight: '3.5vh',
    baseTransform: 'rotate(-12deg)',
    label: 'Ruler',
  },
  {
    id: 'red-pen',
    zIndex: 55,
    maxY: -780,
    width: '15vw',
    style: { top: '68vh', right: '14vw' },
    placeholderColor: '#e03030',
    placeholderHeight: '2.5vh',
    baseTransform: 'rotate(-8deg)',
    label: 'Red Pen',
  },
]
